<?xml version="1.0"?>
<!DOCTYPE inex-topic-file [
<!ENTITY  lt      "lessthan">
<!ENTITY  gt      "greaterthan">
<!ENTITY  amp     "ampersand">
<!ELEMENT inex-topic-file (topic+)>
<!ELEMENT topic (title,castitle,phrasetitle,description,narrative)>
<!ATTLIST topic id CDATA #REQUIRED>
<!ATTLIST topic ct_no CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ELEMENT castitle (#PCDATA)>
<!ELEMENT phrasetitle (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT narrative (#PCDATA)>
]>
<inex-topic-file>
<topic id="2010001" ct_no="314">
  <title>landslide malaysia</title>
  <castitle>//*[about(., landslide malaysia)]</castitle>
  <phrasetitle>landslides in malaysia</phrasetitle>
  <description>Find information about landslides that occur in Malaysia.</description>
  <narrative>I am currently working on a web portal for disseminating natural hazard information in Malaysia. One of the hazard is landslide. This portal includes information from various sources, and Wikipedia articles would be one of the contents source for our portal. For this particular search, i want to collect information about landslides that occur in Malaysia history. Results containing general definitions about landslides, such as causes, prevention, etc. are not relevant. Result elements containing landslide in other countries are not relevant. Results containing other type of natural hazards like flood in Malaysia are also not relevant. Results about landslide victory of elections in Malaysia are not relevant.</narrative>
</topic>
<topic id="2010002" ct_no="315">
  <title>search engine</title>
  <castitle>//article[about(., search engine)]</castitle>
  <phrasetitle>"search engine"</phrasetitle>
  <description>Find information on search engines.</description>
  <narrative>There are a lot of search engines like google, bing etc. I want to know how these search engines work.   I would be satisfied with any information given on how search engines work.</narrative>
</topic>
<topic id="2010003" ct_no="316">
  <title>Monuments of India</title>
  <castitle>//article[about(., Monuments) and about(., India)]//sec[about(.,Monuments of India)]</castitle>
  <phrasetitle>"Monuments" "India"</phrasetitle>
  <description>Find information about the ancient monuments in India. Their history and background.</description>
  <narrative>The sub-continent India is dotted with magnificent monuments showing the incredible artistic work and architecture. These monuments remain as the greatest legacy of the glory of the ancient Indians. These monuments were built under the reign of various emperors in India using the human labor rather than any technology. I am really fascinated by such breathtaking architecture and intricate work and would like to know more about these monuments.     For my own personal interest, I would like to learn more background about the monuments in India built in different architectural styles, in accordance to their beliefs and the history and stylistics of such great monuments.    To be relevant an element should discuss about the monuments in India and history behind it. Information on the country India alone without any information regarding the monuments is not relevant; nor is general information on Indian cultures and traditions.</narrative>
</topic>
<topic id="2010004" ct_no="318">
  <title>Indian food</title>
  <castitle>//article[about(., indian food)]</castitle>
  <phrasetitle>" Indian food "</phrasetitle>
  <description>information about Indian food</description>
  <narrative>India is a vast country with varying cultures, languages, climates and people. Each region in India has its specific food specialty.  Cooking is my hobby and I love Indian food. I always try to cook new Indian dishes.  Following results can be considered relevant. Anything that is related to Indian food, anything related to famous hotels and their favorite dishes. Anything related to various spices, herbs, vegetables, fruits that are grown in India. Anything related to breakfast, lunch, snacks,0 beverages from India.  Following results can be considered irrelevant. The documents which is not related to Indian food anyway. Or the document that just mentions Indian food but does not contain any information related to it.  </narrative>
</topic>
<topic id="2010005" ct_no="319">
  <title>fashion</title>
  <castitle>//article[about(., fashion)]</castitle>
  <phrasetitle>"fashion"</phrasetitle>
  <description>Find information on fashion.</description>
  <narrative>I want to write a report on how fashion has changed over time. I want the results to have everything that is related to fashion so that I can choose topics relevant to me. The topics can range from fashion trends, fashion faux pas, popular fashion, fashion brands, etc.    Fashion also involves all the designers that are associated with fashion. Every decade has a fashion designer who has influenced the up-coming trends. Retrieval of such designer related information is also relevant to the query.    Retrieval of information on trends in different accessories or clothing is also relevant.</narrative>
</topic>
<topic id="2010006" ct_no="320">
  <title>Evolution of Storage devices</title>
  <castitle>//article[about(., Evolution or History of Storage devices) or about(., "Primary or Secondary Storage devices")]//sec[about(., RAM ROM)]</castitle>
  <phrasetitle>"Evolution / History of storage devices"</phrasetitle>
  <description>Find information about the development of storage devices over time.</description>
  <narrative>A Storage device is a major component a computer system. Data has to be stored for various processing needs. With faster technology the need for better and faster storage devices is pertinent.I thought it would be interesting to know about how the storage devices changed over time to see how it catered to the needs with the evolution of technology.</narrative>
</topic>
<topic id="2010007" ct_no="322">
  <title>marilyn monroe played impersonator actor</title>
  <castitle>//article[about(.//(actor|movie|play),marilyn monroe played impersonator)]</castitle>
  <phrasetitle>"played marilyn monroe" "marilyn monroe impersonator" "impersonated marilyn monroe"  "appeared as marilyn monroe"</phrasetitle>
  <description>Looking for a Marilyn Monroe impersonator or actor who played her role</description>
  <narrative>Looking for several actors who played in the role of Maralyn Monroe to interview for a book on her legacy and the different perceptions of her.  Information about the circumstances in connection to Maralin Monroe and sufficinet information to identify the person who is reported to have acted her part is relevant.</narrative>
</topic>
<topic id="2010008" ct_no="323">
  <title>English Literature William Wordsworth</title>
  <castitle>//article[about(., English Literature)]//sec[about(., William Wordsworth )]</castitle>
  <phrasetitle>English Literature "William Wordsworth"</phrasetitle>
  <description>Life of William Wordsworth and his contributions to English Literature</description>
  <narrative>Documents about English Literature in general but with a section on Wordsworth the poet is relevant.  Documents about the life and works of William Wordsworth is particularly relevant. Reviews or analysis of Wordsworth's work is also relevant. A mention to any other Wordsworth is irrelevant here.</narrative>
</topic>
<topic id="2010009" ct_no="324">
  <title>sound synthesis method</title>
  <castitle>//*[about(., sound synthesis method)]</castitle>
  <phrasetitle>"sound synthesis"  method</phrasetitle>
  <description>Find methods for sound synthesis used in musical synthesizers</description>
  <narrative>I want to know what are the methods used for sound synthesis in musical synthesizers. Some mathematics are welcome.</narrative>
</topic>
<topic id="2010010" ct_no="325">
  <title>cheese production</title>
  <castitle>//*[about(., cheese production)]</castitle>
  <phrasetitle/>
  <description>Find methods or recipes used for cheese production</description>
  <narrative>I want to know what methods, process, recipes are used to produce cheese. What are the different steps, if heating/cooling are used, what fungi are involved, if aging is used/recommended, if some kind of milk is preferable,...</narrative>
</topic>
<topic id="2010011" ct_no="326">
  <title>Computer "Operating Systems"</title>
  <castitle>//article[about(., "operating systems")]//sec[about(., "History of operating systems") or about(., "concepts in Operating systems") or about(., "operating system")]</castitle>
  <phrasetitle>"operating system"</phrasetitle>
  <description>Find information about  computer operating systems.</description>
  <narrative>operating systems in computers manage how different programs use the hardware of the system and act as an interface between user and the hardware of the system. These Operating systems are found in most of the devices which can run multiple programs. Some of the well known operating systems are  Microsoft Windows, Mac OS X, Linux, and UNIX.     After reading some technical papers about development of operating systems from the initial stage I gained some interest. I would like to know about the history of computer operating systems, how they evolved, concepts based on which they are designed, comparison between operating systems, different operating system models, examples of operating systems, and components of a operating system. I expect to find large documents which gives some clear explanation/definition of the concepts above. It is fine, if there are some sections in the article about the operating system used along with some description about it.     To be relevant the element should contain discussion about Operating system and the concepts used in it. Usage of the term "operating system" in the article with out including the name of the OS and description about it is not relevant. Just phrasing the name of the Operating system in the article is also not relevant.  </narrative>
</topic>
<topic id="2010012" ct_no="327">
  <title>Bengal Renaissance</title>
  <castitle>//article[about(., "Bengal Renaissance")]</castitle>
  <phrasetitle>"Bengal Renaissance"</phrasetitle>
  <description>Fetch documents about Bengal Renaissance period and eminent personalities during that period.</description>
  <narrative>The documents about history of and the reviews, analysis on Bengal Renaissance period is relevant. The lives and works of eminent personalities during this period is relevant too. Discussions about the upsurge of Indian Independence movement pertaining to this period is also relevant here. Information about any other renaissance period is not sought here.</narrative>
</topic>
<topic id="2010013" ct_no="328">
  <title>rock music genre</title>
  <castitle>//article[about(.,rock music genre)]</castitle>
  <phrasetitle/>
  <description>Find information about genres in rock music</description>
  <narrative>There are many genres in music. Moreover, certain genre has a lot of smaller genres. In this situation, I love to listen to rock music but I do not know well the genre in rock music. So I want to know the genres in rock music. Therefore, the relevant articles should include the genres in rock music while explanations about certain rock music are not irrelevant articles.</narrative>
</topic>
<topic id="2010014" ct_no="329">
  <title>composer museum</title>
  <castitle>//*[about(., composer museum)]</castitle>
  <phrasetitle/>
  <description>Documents or parts of documents that describe or identify a museum dedicated or which has a significant section dedicated to a composer</description>
  <narrative>I want to know the museum that are dedicated to or which have a significant section dedicated to a composer. Other music related museum  which are  not dedicated to a composer are not relevant (for instance a museum of musical  instruments)</narrative>
</topic>
<topic id="2010015" ct_no="330">
  <title>rite passage transition adult</title>
  <castitle>//*[about(., rite passage transition adult)]</castitle>
  <phrasetitle/>
  <description>Find existence and description of rites of passage to the adult status.</description>
  <narrative>I want to know what are the existing rites of passage to the adult status in different communities or culture around the world.</narrative>
</topic>
<topic id="2010016" ct_no="331">
  <title>capital punishment</title>
  <castitle>//*[about(., capital punishment)]</castitle>
  <phrasetitle/>
  <description>What are the states where capital punishment is (or was applied) ? What method of execution are/were used ?</description>
  <narrative>What are the states where capital punishment is (or was) applied?  What method of execution are/were used?</narrative>
</topic>
<topic id="2010017" ct_no="333">
  <title>lady gaga</title>
  <castitle>//article[about(.,lady gaga)]</castitle>
  <phrasetitle>lady gaga</phrasetitle>
  <description>I want to find some information about the famous singer lady gaga.</description>
  <narrative>Recently,lady gaga becomes more and more famous in students of China.So,I want to know more about lada gaga.Articles dedicated to lady gaga is relevant.Articles referring to lady gaga is irrelevant.</narrative>
</topic>
<topic id="2010018" ct_no="334">
  <title>Christopher Columbus and the discovery of America</title>
  <castitle>//article[about(., christopher columbus america discovery)]</castitle>
  <phrasetitle>"Christopher Columbus" "America discovery"</phrasetitle>
  <description>I would like to read documents or parts of them dealing with the discovery of America by Christopher Columbus</description>
  <narrative>I like a lot the history of Spain, and one of its most important events is the discovery of America by Christopher Columbus. So I would like to have the whole sequence of events, previous and posteriorly, related to this discovery, i.e. how Columbus got the idea of reaching the Indias by the West, how he could get the corresponding financing, and all about his several trips to America, with a detail relation of the events that occurred to him in them.    Therefore, a relevant element should deal with any of the previously cited topics of interests. Any reference to America previous to Columbus is not relevant for me, as well as any other element posterior to Columbus's death.</narrative>
</topic>
<topic id="2010019" ct_no="335">
  <title>gallo roman architecture in paris</title>
  <castitle>//*[about(.,gallo roman architecture in paris)]</castitle>
  <phrasetitle>"gallo roman" architecture in paris</phrasetitle>
  <description>"gallo roman" architecture in paris</description>
  <narrative>I am looking for gallo roman architecture ruins, buildings, or remains in or around Paris. Buildings that copy the gallo roman architecture are also relevant for me.  I am making a trip of few days in Paris and I like to find out where I can see such buildings.  </narrative>
</topic>
<topic id="2010020" ct_no="336">
  <title>electricity source in France</title>
  <castitle>//article[about(.,electricity source in France)]</castitle>
  <phrasetitle>electricity source in France</phrasetitle>
  <description>I am looking for information on the sources of information in France.</description>
  <narrative>I would like to know what are the sources of the electric power in France and in the metropole and also in the oversees regions of France. IAny numbers on the percentage of the different sources (nuclear, others, ...) are relevant. I am also interested in the "green" sources of electricity (wing, solar panels) and their current use in France.</narrative>
</topic>
<topic id="2010021" ct_no="337">
  <title>nazi war criminals</title>
  <castitle>//person[about(., nazi war criminals)]</castitle>
  <phrasetitle/>
  <description>Find information about nazi war criminals</description>
  <narrative>I'd like to collect information about nazi engaged in war crimes or crimes against humanity: who they are and which crimes they committed.  It is also interesting for me to know is they were indicted and found guilty or if they aren't still arrested.  </narrative>
</topic>
<topic id="2010022" ct_no="338">
  <title>food specialty italy</title>
  <castitle>//*[about(.,food specialty italy)]</castitle>
  <phrasetitle>food specialty italy</phrasetitle>
  <description>I am kooking for food specialty in Italy</description>
  <narrative>I am planning my holidays in Italy during the summer. I need to know the food specialities in a way to test these. Any food interest me from any region of Italy. Brands of Italian food products are also interesting because they help me to find out what food is produced there.</narrative>
</topic>
<topic id="2010023" ct_no="339">
  <title>retirement age</title>
  <castitle>//*[about(., retirement age)]</castitle>
  <phrasetitle>"retirement age"</phrasetitle>
  <description>I'd like to know the retirement age all over the world</description>
  <narrative>There will be soon a retirement reform in France, and the age of retirement will probably increase.  I'd like to know what is the retirement age in other countries. Is it the same for all people or does this age depend on the job ?  I'm also interested in the history of retirement. Since when is it possible in all countries ? How did the retirement age evolve in time ?    Information about how pensions are calculated is not relevant. Information about health and activities  of retired persons is also not relevant.</narrative>
</topic>
<topic id="2010024" ct_no="340">
  <title>mother's day</title>
  <castitle>//*[about(., mother's day)]</castitle>
  <phrasetitle>"mother's day"</phrasetitle>
  <description>Find information about mother's day all over the world</description>
  <narrative>It will be mother's day next sunday in France. I'd like to have information about this day all over the world: how it is celebrated, what is the history of this day, and what are the related traditions.</narrative>
</topic>
<topic id="2010025" ct_no="341">
  <title>mold health</title>
  <castitle>//article[about(., mold health )]</castitle>
  <phrasetitle/>
  <description>Find information effect of mold on our health</description>
  <narrative>Recently Brita, which is a water cleaner, in our lab was covered with mold. Unfortunately, I should drank some molded water. So, I worry about how the mold effect our body and seek for the information. Therefore documents referring to the effect of the mold, which is fungus, are relevant while detail about the mold or referring to another meanings mold, which similar meanings to molding, are not relevant documents.</narrative>
</topic>
<topic id="2010026" ct_no="342">
  <title>american pre-columbian civilizations</title>
  <castitle>//article[about(., american pre-columbian civilizations)]</castitle>
  <phrasetitle>american pre-columbian civilizations</phrasetitle>
  <description>Find any document, or part of it, describing any aspect of the American pre-columbian civilizations.</description>
  <narrative>I've always been interested in archeology, so I am preparing a trip to different parts of America, where archaeological remains can be visited. In order to make the decision about what countries and places to visit, I would like to read information about the pre-columbian civilizations in America, so I can know more about their culture, history, political organization, relationships or interactions among different civilizations, economy, etc., as well as the remains that can be visited in our days.     Therefore, a relevant element would be related to any aspect of any American pre-columbian civilization, and as its name explain, previously to the arrival of Christopher Columbus. Any element with a content dated in a posterior moment would be not relevant.</narrative>
</topic>
<topic id="2010027" ct_no="343">
  <title>Paul Auster</title>
  <castitle>//*[about(.,Paul Auster)]</castitle>
  <phrasetitle/>
  <description>I want information about the writer Paul Auster</description>
  <narrative>I want information about the writer Paul Auster. Who is he. I would get the list of books he has written and the theme of these books.   I am not interested in the prices or the way to buy these books.</narrative>
</topic>
<topic id="2010028" ct_no="344">
  <title>psychological consultation</title>
  <castitle>//article[about(.,psychological consultation)]</castitle>
  <phrasetitle>psychological consultation</phrasetitle>
  <description>I want to find some information about psychological consultation.</description>
  <narrative>I have endured a lot of pressure from work recently.So,I want to consult some famous psychologist for help.Information about any famous psychologist is relevant.But information about psychology is irrelevant.</narrative>
</topic>
<topic id="2010029" ct_no="346">
  <title>ballet exam</title>
  <castitle>//*[about(., ballet exam)]</castitle>
  <phrasetitle/>
  <description>Information regarding different kinds of ballet exams.</description>
  <narrative>I just started taking up ballet, and I want to know different ballet grade exams for different methods. The result should list the affiliated method (RAD, Russian, etc.), and how many grades are offered etc.</narrative>
</topic>
<topic id="2010030" ct_no="348">
  <title>minimaism art music</title>
  <castitle>//*[about(., minimaism art music)]</castitle>
  <phrasetitle/>
  <description>Find any information relating to minimalistic art, including music.</description>
  <narrative>I am taking an art history class and I need to write a paper regarding what influenced minimalism, what minimalism has influenced in the field of art.     A text that describes non-minimalism art is relevant if it explains the relation between the art and the minimalism. By art, I include not only paintingish and music, but also performing art, and even novels.</narrative>
</topic>
<topic id="2010031" ct_no="349">
  <title>science women few</title>
  <castitle>//*[about(., science women few)]</castitle>
  <phrasetitle/>
  <description>Why are there so few women in sciences?</description>
  <narrative>I'm looking for text that describes possible causes of the scarcity of women in sciences. A text describing women in science, but not the cause of decline is irrelevant. A text describing differences in cognitive abilities of women that could be a cause, but not mentioning women in sciences is still relevant.</narrative>
</topic>
<topic id="2010032" ct_no="350">
  <title>japanese ballerina</title>
  <castitle>//*[about(., japanese ballerina)]</castitle>
  <phrasetitle/>
  <description>Return a list of ballerina of Japanese descent or nationality.</description>
  <narrative>I'm compiling a list of Japanese ballet dancers. Any mention of Japanese ballet dancer, male or female, of (part) Japanese descent, or of Japanese nationality regardless of decent is relevant. Thus an article about a Japanese ballet dancer is relevant, a paragraph mentioning a Japanese ballet dancer in a totally unrelated article is relevant, and a list that only mentions the name with the occupation is also relevant.</narrative>
</topic>
<topic id="2010033" ct_no="351">
  <title>collapse of housing bubble usa</title>
  <castitle>//*[about(., collapse of housing bubble usa)]</castitle>
  <phrasetitle/>
  <description>Find information about the cause and impact of the USA housing bubble in 2000's.</description>
  <narrative>The economy is bad everywhere. I want to learn the cause of the current poor economy, that is the US housing bubble in 2000's and what impact it had, what caused it, and any other information that is useful in preparing for writing a paper for my economics class.    Any information pertaining to US housing bubble is relevant. Housing bubbles in other countries are only relevant if it relates to the US housing bubble. General economic theory of interest rate and housing bubbles is also useful even if it does not mention the particular US housing bubble.</narrative>
</topic>
<topic id="2010034" ct_no="353">
  <title>worm virus</title>
  <castitle>//article[about(.,worm virus)]</castitle>
  <phrasetitle>worm virus</phrasetitle>
  <description>I want to find some information about worm virus.</description>
  <narrative>I major in computer science and recently my computer infected worm virus.So I want to know how it works.Code of any kind of worm virus and what file and process some worm virus creates or modifies is relevant.Information about how to remove worm viruses is irrelevant.</narrative>
</topic>
<topic id="2010035" ct_no="354">
  <title>psychological effects music</title>
  <castitle>//*[about(., psychological effects music)]</castitle>
  <phrasetitle/>
  <description>find information about psychological effects in music</description>
  <narrative>I'm studying psychology, especially I'm interested in the psychology of music. Any document component discussing about some musical effect on the human psyche is of interest.</narrative>
</topic>
<topic id="2010036" ct_no="355">
  <title>northern Finland languages Lapland Sami</title>
  <castitle>//*[about(., northern Finland languages Lapland Sami)]</castitle>
  <phrasetitle/>
  <description>Find information about the languages of Lapland, northern Finland</description>
  <narrative>I'm interested in the history of Finno-Ugrian languages, which are not widely spoken anymore. Any text passage dealing with the history and usage of those languages is of interest. Examples of the languages are Sami and MeÃ¤nkieli.</narrative>
</topic>
<topic id="2010037" ct_no="356">
  <title>social network API</title>
  <castitle>//*[about(.,social network API)]</castitle>
  <phrasetitle/>
  <description>Find the information that is the related technique to social networking service.</description>
  <narrative>In recent year, social networking service (SNS) has attracted much attention. Especially, the "Facebook" and the "Twitter" have been opening aggressively their resource and had released own API. Their techniques has novel business model that is different from past major Web service such as a Web retrieving service and a portal site. Additionally, mentioned the new business model is generating the new internet industry. So, I want to information of technique about applying in SNS without technique of general Web service and non relevant to SNS.</narrative>
</topic>
<topic id="2010038" ct_no="358">
  <title>dinosaur</title>
  <castitle>//article[about(., dinosaur )]</castitle>
  <phrasetitle>"dinosaur"</phrasetitle>
  <description>information about dinosaurs, vertebrate animals who often have enormous size</description>
  <narrative>Dinosaurs are vertebrate animals and often have enormous size. Like many others, I would like to know anything that can help scientific research on dinosaurs such as their categories, features, distinguishing behaviors, evolution, fossils, famous paleontologists who study dinosaurs, dinosaurs related museum, park, books, and geographical location. However, dinosaur fictions are not relevant, including comics, games, movie/film, and animation. Artists such as sculptors are irrelevant as well.</narrative>
</topic>
<topic id="2010039" ct_no="359">
  <title>Emmy Awards</title>
  <castitle>//article[about(., Emmy Awards)]</castitle>
  <phrasetitle/>
  <description>information of Emmy Awards</description>
  <narrative>I want to know something about Emmy Awards. Information, the history of Emmy Awards, awarded actors and TV program for example, is in demand.</narrative>
</topic>
<topic id="2010040" ct_no="361">
  <title>President of the United States</title>
  <castitle>//article[about(., President of the United States )]</castitle>
  <phrasetitle/>
  <description>information of President of the United States</description>
  <narrative>My nephew needs some information about the presidents of the United States for his history homework. Information, introduction of these presidents for example, is in demand.</narrative>
</topic>
<topic id="2010041" ct_no="362">
  <title>Japanese art</title>
  <castitle>//article[about(., Japanese art)]</castitle>
  <phrasetitle/>
  <description>information of japanese art</description>
  <narrative>Japan is a country with long history. Now, I am interested in Japanese traditional arts, flower arrangement，Bushido，Noh and tea ceremony for example. Any information about these arts will be relevant.</narrative>
</topic>
<topic id="2010042" ct_no="363">
  <title>Quilombos settlements and leaders</title>
  <castitle>//article[about(.,quilombo settlement) and about(.,leader)]</castitle>
  <phrasetitle>"Quilombos settlements" "Large Quilombo" "Quilombo leaders"</phrasetitle>
  <description>Information about Quilombo history and leaders</description>
  <narrative>I'm doing some research about slaves rebellion and there influence in Brazilian history.  During my research I've heard about brazilian settlements called Quilombos who where build and ruled by escaped slaves.  I'm trying to get some informations about them: their political structure, some historical facts and their most important leaders.</narrative>
</topic>
<topic id="2010043" ct_no="364">
  <title>List of films from the surrealist category</title>
  <castitle>//movie[about(.,surrealism)]//sec[about(.,films)]</castitle>
  <phrasetitle>"Surrealist directors" "List category surrealist films"</phrasetitle>
  <description>List of films and directors related to surrealism movement</description>
  <narrative>Surrealism was an cultural movement active in various domain from  literature, to visual artwork like painting and sculture.   Sadly it seems that it only marginaly use movie direction.  As a movie-goer and big fan of the surrealistic movement I try to find a list of movies I can watch related to it.  This list must include directors and movie names directly associated and active at the begining of the movement and movies wiche are considered inspired by there codes.</narrative>
</topic>
<topic id="2010044" ct_no="365">